### ISSUE TITLE
Unity 5.2b6 "setting mipmap mode of already created render texture is not supported"

### ISSUE THREAD

**Issue by DeXtmL** [Xerxes1138/UnitySSR#1]
Setting useMipMap and generateMips are not supported as the temporary texture is already created.

UnitySSR.cs  
Line 134

Snippet:
RenderTexture mip = RenderTexture.GetTemporary(size ,size , 16, RenderTextureFormat.ARGBHalf);
mip.isPowerOfTwo = true;
mip.useMipMap = true;
mip.generateMips = true;

It's possible to use permanent texture to bypass this issue. But if custom mipmap generation is needed, Unity fails to render into lower mip levels.
I am not quite familiar with Unity, so this is probably not a good solution. Please investigate.

Windows 7 x64, Nvidia DX11 mode.

**Comment by Xerxes1138** [comment]
Hi,

I couldn't check this before but now that 5.2 is out I can, so I'm currently investigating a solution to this and I hope I'll find a good workaround as mip map are really important to get proper blur without using 256 samples for my blurring.

Thank you for reporting this!
